version: '1.0'
services:
  db:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=piano-respository
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    ports:
      - '5432:5432'